// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4311.subsystems;

import org.usfirst.frc4311.RobotMap;

import edu.wpi.first.wpilibj.*;


import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class wheels extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    CANJaguar cANJaguar4 = RobotMap.wheelsCANJaguar4;
    CANJaguar cANJaguar3 = RobotMap.wheelsCANJaguar3;
    CANJaguar cANJaguar2 = RobotMap.wheelsCANJaguar2;
    CANJaguar cANJaguar1 = RobotMap.wheelsCANJaguar1;
    RobotDrive robotDrive41 = RobotMap.wheelsRobotDrive41;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void setJaguar1(double val) {
    	cANJaguar1.set(val);
    }
    
    public void setJaguar2(double val) {
    	cANJaguar2.set(val);
    }
    
    public void setJaguar3(double val) {
    	cANJaguar3.set(val);
    }
    
    public void setJaguar4(double val) {
    	cANJaguar4.set(val);
    }
}

