// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4311;
    
import edu.wpi.first.wpilibj.*;


import edu.wpi.first.wpilibj.livewindow.LiveWindow;


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANJaguar wheelsCANJaguar4;
    public static CANJaguar wheelsCANJaguar3;
    public static CANJaguar wheelsCANJaguar2;
    public static CANJaguar wheelsCANJaguar1;
    public static RobotDrive wheelsRobotDrive41;
    public static CANJaguar mCANJaguar1;
    public static CANJaguar mCANJaguar2;
    public static RobotDrive mRobotDrive21;
    public static Solenoid sSolenoid2;
    public static SpeedController sSpeedController1;
    public static SpeedController sSpeedController2;
    public static RobotDrive sRobotDrive21;
    public static Solenoid sSolenoid1;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        wheelsCANJaguar4 = new CANJaguar(5);
        
        
        wheelsCANJaguar3 = new CANJaguar(4);
        
        
        wheelsCANJaguar2 = new CANJaguar(3);
        
        
        wheelsCANJaguar1 = new CANJaguar(2);
        
        
        wheelsRobotDrive41 = new RobotDrive(wheelsCANJaguar1, wheelsCANJaguar2,
              wheelsCANJaguar3, wheelsCANJaguar4);
        
        wheelsRobotDrive41.setSafetyEnabled(true);
        wheelsRobotDrive41.setExpiration(0.1);
        wheelsRobotDrive41.setSensitivity(0.5);
        wheelsRobotDrive41.setMaxOutput(1.0);

        mCANJaguar1 = new CANJaguar(6);
        
        
        mCANJaguar2 = new CANJaguar(7);
        
        
        mRobotDrive21 = new RobotDrive(mCANJaguar1, mCANJaguar2);
        
        mRobotDrive21.setSafetyEnabled(true);
        mRobotDrive21.setExpiration(0.1);
        mRobotDrive21.setSensitivity(0.5);
        mRobotDrive21.setMaxOutput(1.0);
        

        sSolenoid2 = new Solenoid(0, 1);
        LiveWindow.addActuator("s", "Solenoid 2", sSolenoid2);
        
        sSpeedController1 = new Talon(0);
        LiveWindow.addActuator("s", "Speed Controller 1", (Talon) sSpeedController1);
        
        sSpeedController2 = new Talon(1);
        LiveWindow.addActuator("s", "Speed Controller 2", (Talon) sSpeedController2);
        
        sRobotDrive21 = new RobotDrive(sSpeedController1, sSpeedController2);
        
        sRobotDrive21.setSafetyEnabled(true);
        sRobotDrive21.setExpiration(0.1);
        sRobotDrive21.setSensitivity(0.5);
        sRobotDrive21.setMaxOutput(1.0);
        

        sSolenoid1 = new Solenoid(0, 0);
        LiveWindow.addActuator("s", "Solenoid 1", sSolenoid1);
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
